on:
  pull_request:
  push:
    branches: [main]

jobs:
  tf_docs:
    name: Render Terraform Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
  pre_commit:
    name: Run pre-commit and commit any autocorrections
    # Depends on tf_docs to avoid conflicts when changes are being written by both tf_docs and pre-commit
    needs: tf_docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6
    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: 0.54.8
        # To avoid rate-limiting
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: terraform-linters/setup-tflint@v3
      name: TFLint - Setup
      with:
        tflint_version: latest

    - name: TFLint - Init
      run: tflint --init
      env:
        # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
        GITHUB_TOKEN: ${{ github.token }}
    - name: TFLint - Show version
      run: tflint --version
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - uses: pre-commit/action@v3.0.0
    - uses: pre-commit-ci/lite-action@v1.0.1
      if: always()
